import type { Metadata } from "next";
import { Tajawal } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import WaterMark from "@/components/WaterMark";

const tajawal = Tajawal({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={tajawal.className}>
        <NavBar />
        <main className="bg-cover bg-no-repeat">{children}</main>
        <WaterMark />
      </body>
    </html>
  );
}
